# Generated by Django 5.0.2 on 2024-03-01 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_donationarea_gallery_volunteer_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donation'),
        ),
    ]
